[package]
name = "snake-server"
version = "0.1.0"
authors = ["Gireg Maury <gireg.maury@student-cs.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
